### ISSUE TITLE
 FileTransfer is not defined

### ISSUE THREAD

**Issue by rajamohammed** [santoshshinde2012/FileTransfer_Upload#1]
Hi i have used your code and injected "cordovafileTransfer" and "cordovaFile" dependencies , but i get the below error  
   ReferenceError: FileTransfer is not defined
    at Object.download (http://192.168.0.2:8100/js/ng-cordova.js:1214:22)
    at Scope.$scope.downloadFile (http://192.168.0.2:8100/js/controllers.js:308:26)

**Comment by rajamohammed** [comment]
The error Resolved after enclosing the cordovaFileTranfer inside a on deviceready event .
